sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: bUpWr3r8Uc2p/qU+rZ0WurAfhlfHWdKEWRR7ha/oipnqWh/tPW9sIx0W+LfelXb1LyqU0mayRx4rRR1QKD5iXhQ0yIxO22d9ccKvjuFT88BMmCbCFdAk1c4/R+C2yOngiR/ZFuBLVbg1ij0TWEkgp/xZ7xU2lNoXQlB2Kw88iQ4v6cdmA5Mdkp0UKdU5RUZUllDf9/y/1/JtF6tRC7si7Rn7749AI4O8AXpsBo1kPJc7K8dDXOwRkMcrExSY9KPtHgFbS53WX5kJlSqSWXUm9sD4x7we1OktWvqCbbQ+qJpY+V5CPuys/ALQWxsOR/ucZ8YOLZ3/Tn/gtcsYHTfUCozMykLo8w7LPV3rgsmd64fiAExIDw94L+siZGoDtqwix2UvxLWXEKhPu8C+7YTC0reZ4Lt+r4PruMbvN3xaPTSbMcRJGY7c1A6qA8FPtNz4DBR2yUwwCyq2qLNdpJDERmYhw2zULXx8SIaKq0iwfM36aMC2/u0XIp9ofxbhY83ISFGhTLXPr8IKAZEUzaKXnpv0HNqiPwlYgqTib0PTspO3umSoEcA7NPbbTyfO9D9ERSNd5xT+odHjNLZOJBfX22Zld2gA67fs4i573EtWDA8f4fhoxTrmY0XmJpVZ31HfMt+Kh8i48PHx5Qt1uPvjl7eJcrovyjRrrSE0luAvoC4=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Stories-by-English-Authors--Africa--Selected-by-Scribners-_1980
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy